### PR TITLE
Breaking: Support TypeScript 3.0

### PR DESCRIPTION
**Pull request by JamesHenry**
As per our existing conventions, this change is marked as Breaking despite the lack of breaking code changes. This is to be explicit to users that the change is significant within their setup. Also this branch is protected as usual, so upstream master changes (if any) will need to be merged into this branch.

This will only be considered for merging once TypeScript 3 is the stable release.

### CODE REVIEW

**Comment by JamesHenry** [comment]
TypeScript 3.0 has been released! We can give it a little time to bed in and then get this merged

**Comment by buschtoens** [comment]
Do you have a timeline for when you want to release this? Can we maybe get a beta? :)

**Comment by j-f1** [comment]
If you’d like a beta, you can install `eslint/typescript-eslint-parser#ts-3.0`, which is this PR. (note that this will probably stop working once the PR gets merged and the branch is removed, though)

**Comment by corbinu** [comment]
@buschtoens I always maintain a fork here that is for the latest version of TypeScript here that I just install as a git dep: https://github.com/corbinu/eslint-plugin-typescript

**Comment by Kocal** [comment]
Thanks you @JamesHenry :slightly_smiling_face:

**Pull request merged**
