### PR TITLE
New: Add type arguments and parameters to AST

### PR DESCRIPTION
**Pull request by Pajn**
For prettier/prettier/issues/13 this information must be preserved in the AST.
I had no idea how to create the test so I just did what seemed reasonable but please correct me if it's wrong.

### CODE REVIEW

**Comment by soda0289** [comment]
I think you will want to use `convertTSTypeParametersToTypeParametersDeclaration()` to convert the typescript type parameters instead of `convertTypeArgumentsToTypeParameters()`

I'm not a 100% sure thou. @JamesHenry do you why there are two functions it seems one is only used for class declarations?

The tests look fine to me.

**Comment by Pajn** [comment]
I understood it as `convertTSTypeParametersToTypeParametersDeclaration` is for declaring them (introducing them in the scope) and `convertTypeArgumentsToTypeParameters` is for passing them, which is what is done in CallExpressions.

I realized that primitive types did not work, which is in my second commit. I'm unsure if I should include that in this PR or not. But I guess the above confusion must be solved first to even see if I modified the correct function :)

**Comment by soda0289** [comment]
@Pajn you could be correct. I just saw that `convertTypeArgumentsToTypeParameters()` is only used for class declarations.

Reading the code I don't think the new expression `const a = new A<B>();` is also not keeping the type arguments. Is this correct? Do you want to add support for this as well?

**Comment by soda0289** [comment]
I also think class declarations do not record the generic type argument on the implement clauses do. For example:
``ts
class A<T> {

}
``

**Comment by Pajn** [comment]
Good catches! Might as well get ass many cases as possible fixed.

**Comment by soda0289** [comment]
Nice looks good!

**Comment by JamesHenry** [comment]
This LGTM, thanks @Pajn! It just needs to be rebased against master

**Comment by Pajn** [comment]
Done. I was unsure on New/Fix again, I can change to what you prefer.

I must say thank you to both of you for being both helpful and very responsive on these PRs!

**Pull request merged**
