### PR TITLE
Breaking: Include type annotation range for Identifiers (fixes #314)

### LINKED ISSUE #314: Incorrect location for typeAnnotation
**What version of `typescript-eslint-parser` are you using?**
806251524424e3ad91e750da0f76b8de25ed0b42

**What code were you trying to parse?**

```js
function x(o: { x: string }) {}
```

**What did you expect to happen?**

I expect that the `Identifier` location to include its typeAnnotation location: 11 - 27.

We do a binary search in order to find the node nearest a comment and because the location is not inclusive, we don't go inside of the identifier and don't attach it correctly :( https://github.com/prettier/prettier/issues/1946

**What happened?**

Right now, it gives me 11 - 12.

```js
      "params": [
        {
          "type": "Identifier",
          "range": [
            11, // <---------
            12 // <---------
          ],
          "loc": {
            "start": {
              "line": 1,
              "column": 11
            },
            "end": {
              "line": 1,
              "column": 12
            }
          },
          "name": "o",
          "typeAnnotation": {
            "type": "TypeAnnotation",
            "loc": {
              "start": {
                "line": 1,
                "column": 14
              },
              "end": {
                "line": 1,
                "column": 27
              }
            },
            "range": [
              14, // <---------
              27 // <---------
            ],
            "typeAnnotation": {
              "type": "TSTypeLiteral",
              "range": [
                14,
                27
              ],
              "loc": {
                "start": {
                  "line": 1,
                  "column": 14
                },
                "end": {
                  "line": 1,
                  "column": 27
                }
              },
              "members": [
                {
                  "type": "TSPropertySignature",
                  "range": [
                    16,
                    25
                  ],
                  "loc": {
                    "start": {
                      "line": 1,
                      "column": 16
                    },
                    "end": {
                      "line": 1,
                      "column": 25
                    }
                  },
                  "optional": false,
                  "computed": false,
                  "key": {
                    "type": "Identifier",
                    "range": [
                      16,
                      17
                    ],
                    "loc": {
                      "start": {
                        "line": 1,
                        "column": 16
                      },
                      "end": {
                        "line": 1,
                        "column": 17
                      }
                    },
                    "name": "x"
                  },
                  "typeAnnotation": {
                    "type": "TypeAnnotation",
                    "loc": {
                      "start": {
                        "line": 1,
                        "column": 19
                      },
                      "end": {
                        "line": 1,
                        "column": 25
                      }
                    },
                    "range": [
                      19,
                      25
                    ],
                    "typeAnnotation": {
                      "type": "TSStringKeyword",
                      "range": [
                        19,
                        25
                      ],
                      "loc": {
                        "start": {
                          "line": 1,
                          "column": 19
                        },
                        "end": {
                          "line": 1,
                          "column": 25
                        }
                      }
                    }
                  },
                  "initializer": null,
                  "accessibility": null,
                  "readonly": false,
                  "static": false,
                  "export": false
                }
              ]
            }
```

### PR DESCRIPTION
**Pull request by soda0289**
I changed range of Identifier nodes used in variable declaration and function parameters. Its a simple change but I might have missed something.

### CODE REVIEW

**Comment by JamesHenry** [comment]
I got chance to dig into this today, and we still have a fundamental difference in how we conclude ranges for typeAnnotations vs how Flow does it for the same source.

Take this example:

```ts
let x   :      string;
```

Flow has the following ranges:
screen shot 2017-06-18 at 18 22 43

Whereas in this PR we currently have:

screen shot 2017-06-18 at 18 30 01


I have a fix for this when it comes to `VariableDeclaration`s (building on this PR) so I'll just push it up for your review @soda0289

**Comment by JamesHenry** [comment]
I rebased against master as it was a little bit behind

**Comment by soda0289** [comment]
Thanks for looking into this. Just to confirm the change now uses the colon token as the initial start value of the type annotation node.

**Comment by JamesHenry** [comment]
@soda0289 Yes, purely based on Flow's precedent of doing that

**Comment by JamesHenry** [comment]
Based on a really quick check, it seems like this change will not require any updates to prettier which is a bonus.

**Comment by JamesHenry** [comment]
@andy-ms Please could you take a look at this also? This would be a solution to https://github.com/JamesHenry/tsep-babylon-test/issues/19

See above for the precedent set by flow, I think it differs slightly from babylon's current output

**Comment by soda0289** [comment]
I have not tested this with eslint yet, not sure if any rules will fail. Will try it out tonight

**Comment by JamesHenry** [comment]
@soda0289 Did you get chance to try it out? How did/were you planning on evaluating it out of interest? Do you have a particular repo set up?

**Comment by soda0289** [comment]
Sorry forgot about this. Was a little busy last week. I have several repos at work that I can run this change under and make sure there are no crashes or false positives.

**Comment by soda0289** [comment]
@JamesHenry 
This does cause an issue with the eslint-plugin-typescript. The rule  typescript/type-annotation-spacing has false positives. Which makes sense since we are changing how the type annotation range is calculated.

**Comment by JamesHenry** [comment]
I think that plugin currently has a number of issues right? I would think it should be pretty straightforward to fix

**Comment by soda0289** [comment]
Yes the plugin does have several issues. Should be good to merge this too.

**Pull request merged**
