### PR TITLE
Breaking: Updated supported TypeScript version to ~2.2.1 (fixes #149)

### LINKED ISSUE #149: How to enable TypeScript 2.1.x Support
This issue was originally tracked here: https://github.com/eslint/typescript-eslint-parser/issues/128, but it has now come to its final resolution.

Unfortunately, there was an unintentional breaking change in TypeScript around how it deals with JSDoc comments within some of its public node utility methods that we rely on in this parser.

TS Issue: https://github.com/Microsoft/TypeScript/issues/13519

That issue has now been fixed, but will not be released as a patch version of TypeScript 2.1.x

**This means that it is not possible to _officially_ support TS 2.1.x in this parser**. We will, of course, work to support 2.2.x as soon as possible.

However, because the necessary changes on our side were actually already made, it is still possible for you to use TypeScript 2.1.x on your project.

You can:
- Install this parser using git: the branch name is `ts-2.1`
- Use `typescript@next` as your TypeScript version (this is the master branch of TypeScript, which contains the fix)

(I _think_ this requires npm 3+ (i.e. Node 6+) because otherwise, the peerDependency conflict would prevent you from installing that combo)

### PR DESCRIPTION
**Pull request by JamesHenry**
TypeScript 2.2 is now the stable release

### CODE REVIEW

**Comment by soda0289** [comment]
Can we remove the check for JSXText now in the last merged pull request #158

**Comment by JamesHenry** [comment]
Ah, thanks for reminding me, @soda0289! Yes, that seems to work just fine 😄

**Comment by soda0289** [comment]
Nice can't wait to upgrade!!

**Comment by JamesHenry** [comment]
@eslint/eslint-team As per message in gitter, please could I get a review and release for this?

**Pull request merged**
