### PR TITLE
New: support JSX fragments (fixes #503)

### LINKED ISSUE #503: JSX fragment causes false positives with no-multi-str
**What version of TypeScript are you using?**
2.9.2

**What version of `typescript-eslint-parser` are you using?**
16.0.1

**What code were you trying to parse?**

```ts
export default function Home() {
  return (
    <>
      {description}
      <br />
      <Options labels={getOptions(questions)} />
    </>
  )
}
```

**What did you expect to happen?**
No errors, because `<></>` is short for `<React.Fragment></React.Fragment>` and `React` is already imported.

**What happened?**
`Multiline support is limited to browsers supporting ES5 only  no-multi-str`

### PR DESCRIPTION
**Pull request by wsabransky**

### CODE REVIEW

**Comment by j-f1** [comment]
Can you add some tests for this?

**Comment by wsabransky** [comment]
@j-f1 done!

**Comment by JamesHenry** [comment]
Thanks, @wsabransky!

**Comment by wsabransky** [comment]
@JamesHenry Thanks, updated snapshots.

There is a disagreement between the TSEP and Babylon parser with the fragment fixtures. I tried upgrading babylon to @babel/parser but it didn't fix the problem. How would you like me to proceed?

**Comment by JamesHenry** [comment]
Hi @wsabransky, I apologise for the inconvenience, but please could reopen this PR over here: https://github.com/JamesHenry/typescript-estree

The core parsing logic is now its own freestanding project. At the moment that project is identical to what this one used to be, so it should be very straightforward for you to port it over.

In terms of the babylon case, you can implement an `ignore` for your specs, check out the fixtures-to-test file for how that is done for other such cases right now.

Thanks again!

**Pull request closed without merging**
