### PR TITLE
Breaking: typescript-estree to 18.0.0 and typescript to 3.2.1

### PR DESCRIPTION
**Pull request by armano2**
This PR contains changes from #576, #584, #589, #590, #591, #592 and deprecates changes from #581

## v18.0.0 - v5.3.0 changes: 
https://github.com/JamesHenry/typescript-estree/compare/v5.3.0...v18.0.0

PRs with changes to ast:
- https://github.com/JamesHenry/typescript-estree/pull/120
- https://github.com/JamesHenry/typescript-estree/pull/118
- https://github.com/JamesHenry/typescript-estree/pull/117
- https://github.com/JamesHenry/typescript-estree/pull/111
- https://github.com/JamesHenry/typescript-estree/pull/108
- https://github.com/JamesHenry/typescript-estree/pull/104
- https://github.com/JamesHenry/typescript-estree/pull/98
- https://github.com/JamesHenry/typescript-estree/pull/91
- https://github.com/JamesHenry/typescript-estree/pull/87
- https://github.com/JamesHenry/typescript-estree/pull/82
- https://github.com/JamesHenry/typescript-estree/pull/79
- https://github.com/JamesHenry/typescript-estree/pull/78
- https://github.com/JamesHenry/typescript-estree/pull/76
- https://github.com/JamesHenry/typescript-estree/pull/75
- https://github.com/JamesHenry/typescript-estree/pull/74
- https://github.com/JamesHenry/typescript-estree/pull/73
- https://github.com/JamesHenry/typescript-estree/pull/71
- https://github.com/JamesHenry/typescript-estree/pull/70
- https://github.com/JamesHenry/typescript-estree/pull/69
- https://github.com/JamesHenry/typescript-estree/pull/68
- https://github.com/JamesHenry/typescript-estree/pull/65
- https://github.com/JamesHenry/typescript-estree/pull/57
- https://github.com/JamesHenry/typescript-estree/pull/48
- https://github.com/JamesHenry/typescript-estree/pull/46
- https://github.com/JamesHenry/typescript-estree/pull/42

fixes: #414, #588, #384, #593

### CODE REVIEW

**Comment by armano2** [comment]
there is one test witch i'm thinking about adding, but i'm unsure if i should do it here or as separate pr:

```js
const { AST_NODE_TYPES } = require("typescript-estree/dist/ast-node-types");
const visitorKeys = require("../../visitor-keys");
const astTypes = Object.keys(AST_NODE_TYPES);
describe("visitor-keys", () => {
    for (const type of astTypes) {
        test(`type ${type} should be present in visitor-keys`, () => {
            expect(visitorKeys).toHaveProperty(type);
        });
    }
});
```

this will ensure that we have all nodes supported by `typescript-estree` in `visitor-keys`

**Comment by JamesHenry** [comment]
@armano2 I am back reviewing PRs on this side of the fence again :)

I'm strongly of the opinion that we should just jump straight to this PR and close your other ones. Thanks for putting all of these different ones together and making the options available.

Maybe we could creates some failing tests related to the missing visitor keys in a follow up PR?

**Comment by armano2** [comment]
should i upgrade it to 16.x.x ?

**Comment by JamesHenry** [comment]
We should be able to release 18 today (the heritage related PR) and then draw a line under the major changes in this batch :)

**Comment by platinumazure** [comment]
@JamesHenry Just to make sure I'm following- are you suggesting that typescript-estree will release 18.x soon and we should jump to that, closing this PR at that point?

@armano2 I agree we can do a follow up PR to add the missing visitor keys- as soon as I'm clear on what version of typescript-estree we want to migrate to (see above), we'll get that in and then have a couple of days where the other PRs will need to rebase- during that time you can write a PR for the new test. Sound good?

**Comment by JamesHenry** [comment]
Yes, exactly 👍

**Comment by JamesHenry** [comment]
18 is out now and should hopefully be the last major change for a little while now. We'll working on catching things up here next

**Comment by armano2** [comment]
ok, PR updated with changes for v18

**Comment by armano2** [comment]
@JamesHenry looks like not all tickets got closed
#588, #384, #593

**Comment by siebertm** [comment]
Are there any plans for a new release soon? This kindof blocks me from upgrading typescript to 3.2...

**Comment by Kovensky** [comment]
A workaround that can be used with `yarn`, as long as you have no `BigInt` syntax in your code, is:

```json
  "resolutions": {
    "**/typescript-eslint-parser/typescript-estree": "6.0.0"
  }
```

This must, of course, be removed as soon as the ecosystem updates, or there will be pain.

**Comment by corbinu** [comment]
I also have been maintaining a kind of nightly @corbinu/typescript-eslint-parser

I will say in the latest version typescript/no-empty-interface seems to be broken so I did turn it off

**Pull request merged**
