### PR TITLE
Fix: Unset text attribute .travis.yml instead of using eol

### PR DESCRIPTION
**Pull request by JamesHenry**

### CODE REVIEW

**Comment by platinumazure** [comment]
Is the issue that `*.yml` doesn't match `.travis.yml` due to the leading dot? Or is it specifically that the Travis file needs to be regarded as non-text?

**Comment by JamesHenry** [comment]
@platinumazure the only known context is here https://github.com/eslint/typescript-eslint-parser/issues/113.

The gitattributes file was originally added to help by a windows user, to help windows users.

Originally the file contained just:
```
 * text=auto
  *.js eol=lf
  *.ts eol=lf
```

But then whenever I opened the project on my mac, I would get unstaged changes on the .travis.yml file, despite no actual diff/changes.

Adding the `*.yml eol=lf` was the original way to fix that - but it _seems_ to have had the side-effect of breaking the release job on jenkins... Which I am guessing is on a linux machine @nzakas?

**Comment by platinumazure** [comment]
Just to get this out of the way, is there anything in the YAML spec which requires that linefeeds be CRLF or LF only?

**Comment by platinumazure** [comment]
Okay, I've done some experimenting and I am fairly confident `*.yml` matches `.travis.yml`.

I think what's going on is the .travis.yml file in the index has CRLF line endings, despite the gitattributes policy specified for *.yml files. As is noted in the gitattributes docs, adding the attribute to gitattributes does not retroactively apply to files that were committed with the wrong LF pattern before the attribute was added. So I guess the PR I would rather see is the result of these operations:

1. Revert the .gitattributes change (so that `*.yml eol=lf` is the last line again)
1. Run `rm .travis.yml`
1. Run `git reset`
1. Run `git add -u`

Hopefully this means that the file will be re-committed with LF changes.

**Comment by ilyavolodin** [comment]
@JamesHenry This wouldn't be the fix, since our release script is ran on Jenkins server, not Travis. So it's very unlikely this change will affect anything.

**Comment by JamesHenry** [comment]
@ilyavolodin do you agree with @platinumazure's proposal?

**Comment by JamesHenry** [comment]
I still don't understand why this is an issue on Jenkins, but not on Travis or locally...

**Comment by JamesHenry** [comment]
But @platinumazure suggestion seems reasonable to me :)

**Comment by ilyavolodin** [comment]
@JamesHenry Sorry, I think I misunderstood the core issue. I think it's worth a try at least. I can merge this in, and try running a release.

**Comment by platinumazure** [comment]
As noted on the chat, I'm okay with merging this in as is just to try to unblock the release. I still hope someone will try [my suggestion here](https://github.com/eslint/typescript-eslint-parser/pull/114#issuecomment-259547458) at some point in the future. :smile:

**Comment by ilyavolodin** [comment]
@nzakas I'm not going to run this release, since this includes a breaking change, and release script will automatically release this as v1.0.0. I'm leaving it up to you to decide if this is ready to be 1.0 release.

**Comment by JamesHenry** [comment]
+1, as agreed on chat, we want to make sure we are all on the same page as to what release this will be

**Comment by nzakas** [comment]
The release will be 1.0.0, that's fine. I think the project is probably solid enough to use with a few caveats.

@JamesHenry I'll leave it up to you which path to take to fix this, and then whoever is around can trigger the release.

Please be sure to update the commit message to include the issue (#113).

**Comment by JamesHenry** [comment]
Thanks, @nzakas!

In which case, I will close this and submit a PR implementing @platinumazure's proposal.

**Pull request closed without merging**
