### PR TITLE
New: Automatically generate TS-specific nodes

### PR DESCRIPTION
**Pull request by nzakas**

### CODE REVIEW

**Comment by nzakas** [comment]
@JamesHenry this is what I had in mind for automatically creating the TypeScript-specific nodes. Seems to work fairly well.

**Comment by JamesHenry** [comment]
This looks great, thanks for putting it together.

Only two things I wanted to note ahead of merging were:
1) Fixing linting error due to no use before define violation (could you add `npm run lint` to the PR build?)
2) Changing the test source files under /typescript to be .ts files for improvement developer experience (i.e. editor not putting red squiggles on everything)

I made those changes and created a PR into your feature branch here (https://github.com/eslint/typescript-eslint-parser/pull/42), so was thinking you could merge that and rebase if you are happy with those suggestions?

**Comment by JamesHenry** [comment]
Hmm, interesting that @eslintbot thinks that the PR is fine, despite the two commits and one of them not being formatted correctly :)

But yeah LGTM 👍

**Comment by nzakas** [comment]
I removed the commit count check because we can squash merge now. :)

**Pull request merged**
