### PR TITLE
Docs: Sets default code block language in issue template to "ts"

### PR DESCRIPTION
**Pull request by mariusschulz**
Sets the default code block language to `ts` so that we get nice syntax highlighting on GitHub. :)

### CODE REVIEW

**Comment by JamesHenry** [comment]
Thanks, @mariusschulz! Every little helps 😄 

Please check out our contributing guidelines for how to format the commit message, and for details on the CLA: https://eslint.org/docs/developer-guide/contributing/

**Comment by mariusschulz** [comment]
Does this count as a change to the docs?

**Comment by JamesHenry** [comment]
Yeah, `Docs:` would be great, thanks!

**Comment by mariusschulz** [comment]
Alright, here's the updated PR. I hope everything looks okay now?

**Comment by JamesHenry** [comment]
Awesome, thanks!

**Pull request merged**
