### PR TITLE
Breaking: Use TSTypeReference for TypeParameters

### PR DESCRIPTION
**Pull request by JamesHenry**
I believe this fixes https://github.com/JamesHenry/tsep-babylon-test/issues/5

### CODE REVIEW

**Comment by zdoc01** [comment]
@JamesHenry - Any thoughts on when this will be published?

**Comment by corbinu** [comment]
@zdoc01 James is on vacation he is planning a release next week. Master is stable though if you want to install the git commit

**Comment by JamesHenry** [comment]
Just released as 5.0.0

**Comment by zdoc01** [comment]
Sweet deal, thanks @JamesHenry & @corbinu!

**Pull request merged**
