### PR TITLE
Chore: Force LF for tsx files

### PR DESCRIPTION
**Pull request by uniqueiniquity**
Same as https://github.com/JamesHenry/typescript-estree/pull/11.

### CODE REVIEW

**Comment by uniqueiniquity** [comment]
@JamesHenry sorry for the delay on this; just making sure I'm all good with my employer before signing it.

**Comment by kaicataldo** [comment]
@uniqueiniquity Friendly ping. It would be great to merge this!

**Comment by uniqueiniquity** [comment]
@kaicataldo @JamesHenry _finally_ good to go on my end. Looks like I need an approving review though.

**Comment by kaicataldo** [comment]
Thanks for contributing!

**Pull request merged**
