### PR TITLE
New: Support TypeScript 2.4 (fixes #321) (#322)

### LINKED ISSUE #321: Support TypeScript 2.4
Main changes to syntax are dynamic imports and string enums. Both should probably "just work" by upgrading the `"typescript"` package.

https://blogs.msdn.microsoft.com/typescript/2017/06/12/announcing-typescript-2-4-rc/

### PR DESCRIPTION
**Pull request by JamesHenry**
**We will only merge this once 2.4 is stable.**

I have opened this PR purely for visibility and documenting issues.

### CODE REVIEW

**Comment by JamesHenry** [comment]
Now that we are appropriately snapshotting tokens, it has surfaced a change in JSDoc behaviour between 2.3 and 2.4

https://github.com/Microsoft/TypeScript/pull/15856

JSDocComments will no longer return their contents as tokens when calling `getChildren()` (as we do during token conversion)

**Comment by JamesHenry** [comment]
@soda0289 and anyone else it is relevant to, just so you know, this PR should not be rebased as the commit hashes are important version numbers for prettier, which is already using TS 2.4 on master.

Unfortunately, I was on automatic pilot and rebased the latest changes and so broke the build over there.

We should use merge commits from now on.

**Comment by SimenB** [comment]
You can protect the branch on github ensuring you're not able to force push to it

**Comment by JamesHenry** [comment]
Good point, @SimenB, we will set that up

**Comment by JamesHenry** [comment]
This branch is now protected
screen shot 2017-06-15 at 18 44 59

**Comment by soda0289** [comment]
typescript 2.4 is released now should be good to merge

**Comment by JamesHenry** [comment]
TypeScript 2.4 is now the latest stable release: https://blogs.msdn.microsoft.com/typescript/2017/06/27/announcing-typescript-2-4/

We can look to merge this once the PR for type annotation location data is in

**Comment by JamesHenry** [comment]
@soda0289 Haha that is insane - less than 10 seconds apart 😄

**Comment by corbinu** [comment]
@soda0289 as we discussed I released eslint-plugin-typescript as eslint-plugin-ts so we can start releasing fixes!

**Comment by corbinu** [comment]
Anything I can do to help?

**Comment by JamesHenry** [comment]
@corbinu There is nothing actually blocking this, we were just letting TypeScript 2.4 bed in a bit more, as there were some early issues with it breaking people's code (high profile cases like RxJS, for example).

TypeScript added an extra compiler flag to work around that particular issue, and I am not aware of any others so I think we are good to go for a release of this.

**Comment by corbinu** [comment]
Ok just was checking since I had some time. I am so happy this project is flourishing has been super useful to me!

**Comment by fruchtose** [comment]
@JamesHenry has anything popped up that would prevent releasing this? I'm really excited for this fix.

**Comment by JamesHenry** [comment]
@fruchtose I'll be releasing it next week, once I am back from vacation. In the meantime, installing it using the GitHub commit should work fine

**Comment by fruchtose** [comment]
Awesome, thanks.

**Comment by JamesHenry** [comment]
Just released as 5.0.0

**Comment by fruchtose** [comment]
Awesome, can't wait to try it.

**Pull request merged**
