### PR TITLE
Breaking: Support TypeScript 2.3 (fixes #232)

### LINKED ISSUE #232: Support TypeScript 2.3
TypeScript 2.3 was recently released as the latest stable version and we should look to support it as soon as possible.

On initial inspection of a broken build, it looks like JSX will be the main area of focus for changes.

### PR DESCRIPTION
**Pull request by azz**
Seems to be a minor fix.

### CODE REVIEW

**Comment by JamesHenry** [comment]
Thanks for the quick digging, @azz!

The fact that this didn't break any existing tests is a clear sign that we should add some as part of this change. Please can you add a relevant JSX test?

Many thanks!

**Comment by JamesHenry** [comment]
Also, we would class this a `Breaking` change, and so the commit message needs to reflect that for our release process to work accordingly.

Reference: eslint.org/docs/developer-guide/contributing/pull-requests

**Comment by azz** [comment]
I was just about to amend the commit to be backwards compatible. Is that something you want me to do?

**Comment by JamesHenry** [comment]
Us changing the officially supported TypeScript version should basically always be a breaking change I think, in order to offer clear indication to our users that they will likely need to make changes to their setups

**Comment by JamesHenry** [comment]
We have two other pending breaking changes to make, so this is great timing!

**Comment by azz** [comment]
> The fact that this didn't break any existing tests is a clear sign that we should add some as part of this change. Please can you add a relevant JSX test?

Not sure what you mean by this. The tests did fail until this change, and the change itself it backwards compatible.

**Comment by JamesHenry** [comment]
RE: The tests - Yes, sorry, I misread the type of change we were making at first.

In terms of backwards compatibility, you added that change and comment after I first looked at it. Please can you remove them again?

I really appreciate we you are trying to do with that, but if we added comments and "version bridges" for every TypeScript version upgrade, this project would become very difficult to manage. This upgrade is trivial, but previous ones were not at all. TypeScript does not follow a strict semver policy, and as mentioned before, the AST structure is naturally not respected at all when it comes to version numbers.

By classifying it as a breaking change, we will automatically release a new major version of the parser and the intention to our users is as clear as it can be.

**Comment by azz** [comment]
> TypeScript does not follow a strict semver policy.

I learnt that the hard way when 2.1 came out...

> In terms of backwards compatibility, you added that change and comment after I first looked at it. Please can you remove them again?

Done.

**Comment by JamesHenry** [comment]
We'll get this in with the other breaking changes and release a new major version 🎉

**Pull request merged**
