### PR TITLE
Breaking: typescript-estree to 13.5.2 and typescript to 3.2.1

### PR DESCRIPTION
**Pull request by armano2**
This PR contains changes from #576, #584, #589, #590, #591 and deprecates changes from #581

## v13.5.1 - v12.0.0 changes: 
https://github.com/JamesHenry/typescript-estree/compare/v12.0.0...v13.5.1

changes with master: https://github.com/JamesHenry/typescript-estree/compare/v5.3.0...v13.5.1

PRs with changes to ast:
- https://github.com/JamesHenry/typescript-estree/pull/98
- https://github.com/JamesHenry/typescript-estree/pull/91

---------------

- node `TSNamespaceFunctionDeclaration` is no longer present in AST
- nodes `TSEmptyBodyDeclareFunction` and `TSEmptyBodyFunctionDeclaration` are now unified to `TSDeclareFunction`
- node `FunctionDeclaration` will be `TSDeclareFunction` if there is no body present.

fixes: #414, #588, #384, #593

### CODE REVIEW

**Comment by platinumazure** [comment]
I haven't had a chance to discuss with other team members how best to do the releases for these changes, so here's a straw proposal: I would like to do releases for the latest typescript-estree corresponding with each Typescript version. So for example, this PR has the latest release for Typescript 3.2.1. I don't have a strong desire to release for every version of Typescript, so if we (for example) don't have a PR for a typescript-estree release for 3.2.0, we don't need to create one. In this way, there'll be at least one typescript-eslint-parser release for most Typescript versions.

@armano2 Could you please comment here with which PRs correspond with each Typescript version? Don't close the other PRs yet, in case we end up going a different direction.

@kaicataldo @mysticatea Thoughts on the proposal above?

**Comment by armano2** [comment]
starting from `typescript-estree` v6 there is support for typescript 3.2.1

all my prs except https://github.com/eslint/typescript-eslint-parser/pull/583 are from versions above it.

latest version of `typescript-estree` with before 3.2.1 is currently used one.

**Comment by JamesHenry** [comment]
@platinumazure Please see my comment here: https://github.com/eslint/typescript-eslint-parser/pull/584#issuecomment-453097356

**Comment by JamesHenry** [comment]
Closing in favour of https://github.com/eslint/typescript-eslint-parser/pull/596

**Pull request closed without merging**
