### PR TITLE
Chore: Add test for constructor with parameters

### PR DESCRIPTION
**Pull request by soda0289**
Here is a test that has a class constructor with two parameters. 

I noticed we are missing a lot of tests for newer version of ecmascript like async/await functions. As well as tests for class methods with default parameters, deconstructed parameters, and rest parameters. 

@JamesHenry Let me know if you want me to add more tests.

### CODE REVIEW

**Comment by weirdpattern** [comment]
@JamesHenry do we need a test with initializers and rest params as well?

**Comment by weirdpattern** [comment]
the current test LGTM

**Comment by JamesHenry** [comment]
Yes please! That would be perfect. Looks great so far @soda0289

**Comment by soda0289** [comment]
@weirdpattern @JamesHenry I have added tests for rest parameters, default parameters, and destructing parameters for both class method and constructors.

Let me know if you think we need any more

**Comment by weirdpattern** [comment]
LGTM, thank you @soda0289

**Comment by JamesHenry** [comment]
Great, thanks!

**Pull request merged**
