### PR TITLE
Breaking: fix wrong node type on expressions (fixes #467)

### LINKED ISSUE #467: Wrong AST type in LHS of AssignmentExpression
**What version of TypeScript are you using?**

2.8.1

**What version of `typescript-eslint-parser` are you using?**

15.0.0

**What code were you trying to parse?**

```ts
foo({}).x = 1
```

> http://astexplorer.net/#/gist/6d732ddcc3b1d7d09d74c7f3f2ee802b/094e60c05037e1502789340402db35c0dd835b1b

**What did you expect to happen?**

The `{}` in above code is an `ObjectExpression`.

**What happened?**

The `{}` in above code is an `ObjectPattern`.

And it's same for `ArrayExpression`/`ArrayPattern`.

### PR DESCRIPTION
**Pull request by g-plane**
Fixes #467 

Please tell me if there is something missing.

### CODE REVIEW

**Comment by JamesHenry** [comment]
Thanks, @g-plane, we'll definitely need some tests around this before we can consider merging

**Comment by g-plane** [comment]
@JamesHenry I have added the tests.

**Comment by JamesHenry** [comment]
Thanks @g-plane! This is actually a breaking change for consumers of this project.

If you don't get around to updating the commit message / PR title to be `Breaking`, I can do it on merge.

@mysticatea Please could you review this as you raised the original issue

**Comment by g-plane** [comment]
I've just updated the PR title.

**Comment by JamesHenry** [comment]
Thanks for opening the PR on the new repo already, @g-plane!

**Pull request closed without merging**
