### PR TITLE
Update: added handler for AsExpression TS node.kind

### PR DESCRIPTION
**Pull request by valorkin**
In typescript you can give a hint to tsc about variable type
using keyword as

(node as ts.BinaryExpression).operatorToken;
currently it throws an exception

### CODE REVIEW

**Comment by nzakas** [comment]
Same comment as the other PR: please follow the regular ESLint pull request guidelines (http://eslint.org/docs/developer-guide/contributing/pull-requests)

In this case, we'd need an issue reference and the commit summary format to be updated.

**Comment by nzakas** [comment]
The output from this code is incorrect. Also, please don't add additional files that aren't related to the issue you're trying to fix.

Let's discuss back on #25 what the correct output should be.

**Comment by valorkin** [comment]
> Also, please don't add additional files that aren't related to the issue you're trying to fix.
@nzakas `.editorconfig` or ignoring IDE files?
or fixtures?

**Comment by nzakas** [comment]
`.editorconfig` mostly.

**Comment by valorkin** [comment]
@nzakas ok, I can create mega PR with `.editorconfig`
or you have some agains this config?

**Comment by nzakas** [comment]
It should just be in a separate PR, since I can't merge this one due to what I said on #25.

**Comment by nzakas** [comment]
Closing per discussion on #25.

**Pull request closed without merging**
