### PR TITLE
Breaking: Updated to TypeScript 2.x (fixes #105)

### LINKED ISSUE #105: TypeScript 2.x Support
- [x] Update typescript peerDependency to `^2.0.3` (https://github.com/eslint/typescript-eslint-parser/pull/112)
- Investigate and fix broken tests caused by updated dependency:
  - [x] `jsx/tag-names-with-dots` (https://github.com/eslint/typescript-eslint-parser/pull/108)
  - [x] `jsx/tag-names-with-multi-dots` (https://github.com/eslint/typescript-eslint-parser/pull/108)
  - [x] `basics/declare-namespace-with-exported-function` (https://github.com/eslint/typescript-eslint-parser/pull/107)
  - [x] `decorators/method-decorators/method-decorator-factory-instance-member` (https://github.com/eslint/typescript-eslint-parser/pull/106)
  - [x] `decorators/method-decorators/method-decorator-instance-member` (https://github.com/eslint/typescript-eslint-parser/pull/106)
---
- Transform new constructs introduced in TypeScript 2 (see #90 for additional background)
  - [x] shorthand ambient module declarations (https://github.com/eslint/typescript-eslint-parser/pull/109)
  - [x] non-null assertion operator (https://github.com/eslint/typescript-eslint-parser/pull/110)
  - [x] typed usages of `this` (https://github.com/eslint/typescript-eslint-parser/pull/112)

---
- [x] Add parameter type annotations to the AST (requisite for typed-this) (https://github.com/eslint/typescript-eslint-parser/pull/111)

### PR DESCRIPTION
**Pull request by JamesHenry**
@nzakas As soon as you are happy for this to go in, please publish an npm release for it 😄  🎉 

Fixes https://github.com/eslint/typescript-eslint-parser/issues/50 and #105

### CODE REVIEW

**Comment by nzakas** [comment]
All right, publishing a release now. I'll leave it to you to test it out and see how it goes. :)

**Comment by bradleyayers** [comment]
I'm keen to give this a test run, but I don't see a release yet.

**Comment by ilyavolodin** [comment]
@nzakas Release script failed yesterday. Unfortunately logs don't provide any information as to why...

**Comment by nzakas** [comment]
Yeah, I saw that later, Opened an issue: https://github.com/eslint/typescript-eslint-parser/issues/113

**Pull request merged**
