### PR TITLE
Fix: Replace removed API with public flags (fixes #498)

### LINKED ISSUE #498: Parse error with TypeScript 3
**What version of TypeScript are you using?**

`3.0.0-rc`

**What version of `typescript-eslint-parser` are you using?**

`16.0.1`

**What code were you trying to parse?**

Any codes.

**What did you expect to happen?**

It parses.

**What happened?**

`Parsing error: ts.unescapeIdentifier is not a function`

[Deprecated functions were removed for the major version update.](https://github.com/Microsoft/TypeScript/wiki/API-Breaking-Changes#typescript-30)

https://github.com/eslint/typescript-eslint-parser/blob/3c874ec8b795fcf021c9634403a012c28a300dc6/lib/node-utils.js#L510

### PR DESCRIPTION
**Pull request by texastoland**
LGTM on master except maybe the version change to TypeScript.

### CODE REVIEW

**Comment by texastoland** [comment]
Looks like the build failure just needs restarted?

**Comment by j-f1** [comment]
@texastoland you can close & reopen the PR to restart the build.

**Comment by texastoland** [comment]
I'll wait a day or so to make sure there's nothing else to fix first.

**Comment by texastoland** [comment]
🛎 ping 💢

**Comment by sbason** [comment]
Would love this to be merged if it works :)

**Comment by JamesHenry** [comment]
TypeScript 3 support needs to be managed in its own branch until it is the stable release. I will create a protected branch for that now and you can use that as the target for the PR. You can then install from that branch on github if you are using the RC.

Please also keep PRs focused on one thing, rather than tweaking multiple unrelated things.

**Comment by JamesHenry** [comment]
The TypeScript 3 branch is now available: `ts-3.0`

https://github.com/eslint/typescript-eslint-parser/tree/ts-3.0

Please open a new PR with that as the base

**Comment by texastoland** [comment]
@JamesHenry per the issue summary this issue has no changes specific to TypeScript 3. The parser has been using internal and deprecated APIs for a long time. Per my last comment and the commit diff none of the tests had to change. This is strictly a patch version for master. I can remove the commit updating `package.json`.

**Comment by texastoland** [comment]
Move to reopen please.

**Comment by JamesHenry** [comment]
Please remove the TypeScript upgrade, then we can merge it

**Comment by JamesHenry** [comment]
A new PR can always be opened at least! :)

**Pull request closed without merging**
